CREATE TABLE table_parts (
	spir_project_id int NOT NULL,
	spir_machine_id int NULL,
	spir_group_id int NULL,
	asset_number varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	german_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	portuguese_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	italian_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	installed_quantity int NULL,
	total_quantity_installed int NULL,
	[position] varchar(150) COLLATE Latin1_General_CI_AS NULL,
	section_number varchar(30) COLLATE Latin1_General_CI_AS NULL,
	long_desc varchar(150) COLLATE Latin1_General_CI_AS NULL,
	superseded_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	superseded_chain varchar(500) COLLATE Latin1_General_CI_AS NULL,
	assembly_drawing varchar(150) COLLATE Latin1_General_CI_AS NULL,
	balloon_number varchar(150) COLLATE Latin1_General_CI_AS NULL,
	pandid_tag_note varchar(150) COLLATE Latin1_General_CI_AS NULL,
	price_euro numeric(14,4) NULL,
	delivery_time int NULL,
	machine_serial_number varchar(150) COLLATE Latin1_General_CI_AS NULL,
	parent_asset_number varchar(30) COLLATE Latin1_General_CI_AS NULL,
	material varchar(150) COLLATE Latin1_General_CI_AS NULL,
	cust_note1 varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	cust_note2 varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	cust_note3 varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	cost_euro numeric(12,4) NULL,
	nao_euro numeric(12,4) NULL,
	cost_nao_euro numeric(12,4) NULL,
	cm_percent numeric(12,4) NULL,
	cm numeric(14,4) NULL,
	supplier_name varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	supplier_part_no varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer_serial_number varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	ioc varchar(1) COLLATE Latin1_General_CI_AS NULL,
	fee varchar(1) COLLATE Latin1_General_CI_AS NULL,
	material_code_desc_generic varchar(240) COLLATE Latin1_General_CI_AS NULL,
	created_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	creation_date smalldatetime NULL,
	updated_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	update_date smalldatetime NULL,
	final_material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	material_code_path varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	hierarchy_level int NULL,
	maintenance_code varchar(150) COLLATE Latin1_General_CI_AS NULL,
	capital_flag varchar(1) COLLATE Latin1_General_CI_AS NULL,
	generic_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	german_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	mark nvarchar(1) COLLATE Latin1_General_CI_AS NULL,
	Added varchar(1) COLLATE Latin1_General_CI_AS NULL,
	out_of_boundary varchar(1) COLLATE Latin1_General_CI_AS NULL,
	line_asset_status varchar(30) COLLATE Latin1_General_CI_AS NULL,
	DM numeric(20,2) NULL,
	DL numeric(20,2) NULL,
	FO numeric(20,2) NULL,
	COST_DATE date NULL,
	LIST_PRICE_DATE date NULL,
	MOR numeric(20,2) NULL,
	PRICE_CATEGORY_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_VALUE_WEIGHT_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY varchar(3) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAM_TYPE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	STD_LT numeric(20,2) NULL,
	pandid numeric(20,2) NULL,
	tag numeric(20,2) NULL,
	min_sell_qty int NULL,
	asset_order int NULL,
	family_plant varchar(100) COLLATE Latin1_General_CI_AS NULL,
	priceEstimated varchar(5) COLLATE Latin1_General_CI_AS NULL,
	PHY_CUST_STOCK varchar(30) COLLATE Latin1_General_CI_AS NULL,
	soTag varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soRequestState varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soNumber varchar(150) COLLATE Latin1_General_CI_AS NULL,
	CPMNotes varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	totQtyMandSP int NULL,
	error_message varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	businessID varchar(100) COLLATE Latin1_General_CI_AS NULL,
	soCreation varchar(100) COLLATE Latin1_General_CI_AS NULL,
	soRequest varchar(100) COLLATE Latin1_General_CI_AS NULL,
	om_price numeric(12,4) NULL,
	om_lead_time int NULL,
	original_maintenance_code varchar(100) COLLATE Latin1_General_CI_AS NULL,
	position_offset int NULL,
	upload_excel_position int NULL,
	downloaded_excel_position int NULL,
	spir_line_id int NULL,
	om_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	order_quantity_uom varchar(2) COLLATE Latin1_General_CI_AS NULL,
	om_status varchar(40) COLLATE Latin1_General_CI_AS NULL,
	om_note varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	on_hand_availability numeric(20,4) NULL,
	om_quantity int NULL,
	om_user_item_descr varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	revision int NULL,
	revision_date datetime NULL,
	line_status varchar(50) COLLATE Latin1_General_CI_AS NULL,
	REORDERED_POLICY varchar(50) COLLATE Latin1_General_CI_AS NULL,
	SOFT_ITEM_SELLING_LT varchar(50) COLLATE Latin1_General_CI_AS NULL,
	lineInOut varchar(10) COLLATE Latin1_General_CI_AS NULL,
	adjustedQuantity int NULL,
	finalQuantity int NULL,
	CONSTRAINT table_parts_pk PRIMARY KEY (spir_project_id,asset_number),
	CONSTRAINT table_parts_fk FOREIGN KEY (spir_group_id) REFERENCES table_group(spir_group_id),
	CONSTRAINT table_parts_fk_1 FOREIGN KEY (spir_machine_id) REFERENCES table_machine(spir_machine_id),
	CONSTRAINT table_parts_fk_2 FOREIGN KEY (spir_project_id) REFERENCES table_project(spir_project_id)
);

CREATE TABLE table_parts_grouped (
	group_id int NOT NULL,
	spir_project_id int NOT NULL,
	tot_qty_one_machine int NOT NULL,
	tot_qty_all_machines int NULL,
	[position] int NOT NULL,
	section_number varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	german_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	material_code_description varchar(240) COLLATE Latin1_General_CI_AS NULL,
	long_desc varchar(150) COLLATE Latin1_General_CI_AS NULL,
	pandid_tag_note varchar(150) COLLATE Latin1_General_CI_AS NULL,
	material varchar(150) COLLATE Latin1_General_CI_AS NULL,
	cust_note1 varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	cust_note2 varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	cust_note3 varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	superseded_chain varchar(500) COLLATE Latin1_General_CI_AS NULL,
	final_material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	assembly_drawing varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	balloon_number varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	maintenance_code varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	material_code_path varchar(4000) COLLATE Latin1_General_CI_AS NOT NULL,
	hierarchy_level int NULL,
	price_euro numeric(14,4) NULL,
	delivery_time int NULL,
	cost_euro numeric(12,4) NULL,
	cost_nao_euro numeric(12,4) NULL,
	nao_euro numeric(12,4) NULL,
	cm numeric(14,4) NULL,
	cm_percent numeric(12,4) NULL,
	supplier_name varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	supplier_part_no varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer_serial_number varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	ioc varchar(1) COLLATE Latin1_General_CI_AS NULL,
	fee varchar(1) COLLATE Latin1_General_CI_AS NULL,
	serialnumbers varchar(2000) COLLATE Latin1_General_CI_AS NULL,
	no_of_machines int NULL,
	display_position int NULL,
	capital_flag varchar(1) COLLATE Latin1_General_CI_AS NULL,
	generic_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	german_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	portuguese_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	italian_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	Added varchar(1) COLLATE Latin1_General_CI_AS NULL,
	out_of_boundary varchar(1) COLLATE Latin1_General_CI_AS NULL,
	om_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	order_quantity_uom varchar(2) COLLATE Latin1_General_CI_AS NULL,
	om_status varchar(40) COLLATE Latin1_General_CI_AS NULL,
	om_note varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	on_hand_availability numeric(20,4) NULL,
	om_quantity int NULL,
	om_user_item_descr varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	line_asset_status varchar(30) COLLATE Latin1_General_CI_AS NULL,
	DM numeric(20,2) NULL,
	DL numeric(20,2) NULL,
	FO numeric(20,2) NULL,
	COST_DATE date NULL,
	LIST_PRICE_DATE date NULL,
	MOR numeric(20,2) NULL,
	PRICE_CATEGORY_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_VALUE_WEIGHT_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY varchar(3) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAM_TYPE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	STD_LT numeric(20,2) NULL,
	pandid numeric(20,2) NULL,
	tag numeric(20,2) NULL,
	min_sell_qty int NULL,
	asset_order int NULL,
	saved varchar(5) COLLATE Latin1_General_CI_AS NULL,
	as_sold_deleted varchar(1) COLLATE Latin1_General_CI_AS NULL,
	family_plant varchar(10) COLLATE Latin1_General_CI_AS NULL,
	START_DATE_ACTIVE date NULL,
	END_DATE_ACTIVE date NULL,
	PHY_CUST_STOCK varchar(30) COLLATE Latin1_General_CI_AS NULL,
	soTag varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soCreation varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soNumber varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soRequest varchar(150) COLLATE Latin1_General_CI_AS NULL,
	CPMNotes varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	totQtyMandSP int NULL,
	soRequestState varchar(150) COLLATE Latin1_General_CI_AS NULL,
	priceEstimated varchar(5) COLLATE Latin1_General_CI_AS NULL,
	error_message varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	businessID varchar(100) COLLATE Latin1_General_CI_AS NULL,
	om_price numeric(12,4) NULL,
	om_lead_time int NULL,
	spir_line_id int DEFAULT NEXT VALUE FOR parts_grouped_line_id_seq NOT NULL,
	downloaded_excel_position int NULL,
	upload_excel_position int NULL,
	line_status varchar(50) COLLATE Latin1_General_CI_AS NULL,
	transaction_id varchar(100) COLLATE Latin1_General_CI_AS NULL,
	revision int NULL,
	revision_date datetime NULL,
	original_spir_id int NULL,
	bpm_quantity int NULL,
	original_maintenance_code varchar(100) COLLATE Latin1_General_CI_AS NULL,
	position_offset int NULL,
	bpm_validation_qty int NULL,
	reordered_policy varchar(50) COLLATE Latin1_General_CI_AS NULL,
	soft_item_selling_lt varchar(50) COLLATE Latin1_General_CI_AS NULL,
	adjustedQuantity int NULL,
	finalQuantity int NULL,
	lineInOut varchar(10) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT table_parts_grouped_PK PRIMARY KEY (spir_line_id)
);
 CREATE NONCLUSTERED INDEX NCI_IX_SpirCreation ON table_parts_grouped (  spir_project_id ASC  , final_material_code ASC  )  
	 INCLUDE ( maintenance_code , serialnumbers , tot_qty_all_machines , tot_qty_one_machine ) 
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

CREATE TABLE table_refresh_data (
	spir_project_id int NOT NULL,
	spir_group_id int NOT NULL,
	machine_section_number varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	final_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	assembly_drawing varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	balloon_number varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	total_installed_quantity numeric(38,20) NOT NULL,
	hierarchy_path varchar(4000) COLLATE Latin1_General_CI_AS NOT NULL,
	maintenance_code varchar(150) COLLATE Latin1_General_CI_AS NULL,
	[action] varchar(1) COLLATE Latin1_General_CI_AS NOT NULL,
	event_date smalldatetime NOT NULL,
	created_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	old_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	new_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	processed varchar(1) COLLATE Latin1_General_CI_AS NULL
);
 CREATE NONCLUSTERED INDEX table_spir_refresh_data_maintenance_code_IDX ON table_refresh_data (  maintenance_code ASC  )
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

CREATE TABLE table_locked_codes (
	spir_project_id int NOT NULL,
	machine_serial_number varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	note varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	include_in_spir varchar(1) COLLATE Latin1_General_CI_AS NULL,
	total_quantity_installed int NULL,
	created_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	creation_date smalldatetime NULL,
	updated_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	update_date smalldatetime NULL,
	[position] int NOT NULL,
	[section] varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	save_note varchar(1) COLLATE Latin1_General_CI_AS NULL,
	generic_description varchar(250) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT table_locked_codes_PK PRIMARY KEY (spir_project_id,machine_serial_number,material_code,[position],[section])
);
 CREATE NONCLUSTERED INDEX table_locked_codes_spir_project_id_IDX ON table_locked_codes (  spir_project_id ASC  , material_code ASC  )
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;

CREATE TABLE table_locked_codes_replaced_by (
	spir_project_id int NOT NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	replaced_by varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	replacement_source varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	total_quantity_installed_user int NULL,
	created_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	creation_date smalldatetime NULL,
	updated_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	update_date smalldatetime NULL,
	machine_serial_number varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	[position] int NOT NULL,
	[section] varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	german_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	portuguese_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	italian_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	superseded_chain varchar(500) COLLATE Latin1_General_CI_AS NULL,
	price_euro numeric(12,4) NULL,
	delivery_time int NULL,
	material varchar(150) COLLATE Latin1_General_CI_AS NULL,
	Cost_euro varchar(100) COLLATE Latin1_General_CI_AS NULL,
	nao_euro varchar(100) COLLATE Latin1_General_CI_AS NULL,
	Cost_nao_euro varchar(100) COLLATE Latin1_General_CI_AS NULL,
	Cm_percent varchar(100) COLLATE Latin1_General_CI_AS NULL,
	Cm varchar(100) COLLATE Latin1_General_CI_AS NULL,
	supplier_name varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	supplier_part_no varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer_serial_number varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	material_code_desc_generic varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	Capital_flag varchar(1) COLLATE Latin1_General_CI_AS NULL,
	DM numeric(20,2) NULL,
	DL numeric(20,2) NULL,
	FO numeric(20,2) NULL,
	COST_DATE date NULL,
	LIST_PRICE_DATE date NULL,
	MOR numeric(20,2) NULL,
	PRICE_CATEGORY_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_VALUE_WEIGHT_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY varchar(3) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAM_TYPE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	STD_LT numeric(20,2) NULL,
	min_sell_qty int NULL,
	family_plant varchar(100) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT table_locked_codes_replaced_by_PK PRIMARY KEY (spir_project_id,replaced_by,[section],material_code,machine_serial_number,[position]),
	CONSTRAINT table_locked_codes_replaced_by_FK FOREIGN KEY (spir_project_id,machine_serial_number,material_code,[position],[section]) REFERENCES table_locked_codes(spir_project_id,machine_serial_number,material_code,[position],[section])
);

CREATE TABLE table_parts_grouped_recalc (
	group_id int NULL,
	spir_project_id int NOT NULL,
	tot_qty_one_machine int NULL,
	tot_qty_all_machines int NULL,
	[position] int NOT NULL,
	section_number varchar(30) COLLATE Latin1_General_CI_AS NULL,
	german_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	material_code_description varchar(240) COLLATE Latin1_General_CI_AS NULL,
	long_desc varchar(150) COLLATE Latin1_General_CI_AS NULL,
	pandid_tag_note varchar(150) COLLATE Latin1_General_CI_AS NULL,
	material varchar(150) COLLATE Latin1_General_CI_AS NULL,
	cust_note1 varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	cust_note2 varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	cust_note3 varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	superseded_chain nvarchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	final_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	assembly_drawing varchar(150) COLLATE Latin1_General_CI_AS NULL,
	balloon_number varchar(150) COLLATE Latin1_General_CI_AS NULL,
	maintenance_code varchar(150) COLLATE Latin1_General_CI_AS NULL,
	material_code_path varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	hierarchy_level int NULL,
	price_euro numeric(12,4) NULL,
	delivery_time int NULL,
	cost_euro numeric(12,4) NULL,
	cost_nao_euro numeric(12,4) NULL,
	nao_euro numeric(12,4) NULL,
	cm numeric(12,4) NULL,
	cm_percent numeric(12,4) NULL,
	supplier_name varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	supplier_part_no varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	manufacturer_serial_number varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	ioc varchar(1) COLLATE Latin1_General_CI_AS NULL,
	fee varchar(1) COLLATE Latin1_General_CI_AS NULL,
	SerialNumbers nvarchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	no_of_machines int NULL,
	display_position int NOT NULL,
	capital_flag varchar(1) COLLATE Latin1_General_CI_AS NULL,
	generic_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	french_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	english_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	german_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	portuguese_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	italian_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	spanish_asset_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	processed varchar(1) COLLATE Latin1_General_CI_AS NULL,
	Added varchar(1) COLLATE Latin1_General_CI_AS NULL,
	om_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	order_quantity_uom varchar(2) COLLATE Latin1_General_CI_AS NULL,
	om_status varchar(40) COLLATE Latin1_General_CI_AS NULL,
	om_note varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	on_hand_availability int NULL,
	om_quantity int NULL,
	om_user_item_descr varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	DM numeric(20,2) NULL,
	DL numeric(20,2) NULL,
	FO numeric(20,2) NULL,
	COST_DATE date NULL,
	LIST_PRICE_DATE date NULL,
	MOR numeric(20,2) NULL,
	PRICE_CATEGORY_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_VALUE_WEIGHT_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY varchar(3) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAMILY_CAPITAL_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_CODE varchar(250) COLLATE Latin1_General_CI_AS NULL,
	ABC_HOUSE_NAME varchar(250) COLLATE Latin1_General_CI_AS NULL,
	FAM_TYPE varchar(2) COLLATE Latin1_General_CI_AS NULL,
	STD_LT numeric(20,2) NULL,
	event_date smalldatetime NULL,
	out_of_boundary varchar(1) COLLATE Latin1_General_CI_AS NULL,
	min_sell_qty int NULL,
	asset_order int NULL,
	START_DATE_ACTIVE date NULL,
	END_DATE_ACTIVE date NULL,
	PHY_CUST_STOCK varchar(30) COLLATE Latin1_General_CI_AS NULL,
	soTag varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soCreation varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soNumber varchar(150) COLLATE Latin1_General_CI_AS NULL,
	soRequest varchar(150) COLLATE Latin1_General_CI_AS NULL,
	CPMNotes varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	totQtyMandSP int NULL,
	line_asset_status varchar(30) COLLATE Latin1_General_CI_AS NULL,
	pandid numeric(20,2) NULL,
	tag numeric(20,2) NULL,
	as_sold_deleted varchar(1) COLLATE Latin1_General_CI_AS NULL,
	family_plant varchar(10) COLLATE Latin1_General_CI_AS NULL,
	soRequestState varchar(150) COLLATE Latin1_General_CI_AS NULL,
	priceEstimated varchar(5) COLLATE Latin1_General_CI_AS NULL,
	error_message varchar(MAX) COLLATE Latin1_General_CI_AS NULL,
	businessID varchar(100) COLLATE Latin1_General_CI_AS NULL,
	om_price numeric(12,4) NULL,
	om_lead_time int NULL,
	spir_line_id int NULL,
	downloaded_excel_position int NULL,
	upload_excel_position int NULL,
	position_offset int NULL,
	revision int NULL,
	revision_date datetime NULL,
	original_maintenance_code varchar(150) COLLATE Latin1_General_CI_AS NULL,
	line_status varchar(50) COLLATE Latin1_General_CI_AS NULL,
	adjustedQuantity int NULL,
	finalQuantity int NULL,
	lineInOut varchar(10) COLLATE Latin1_General_CI_AS NULL,
	REORDERED_POLICY varchar(50) COLLATE Latin1_General_CI_AS NULL,
	SOFT_ITEM_SELLING_LT varchar(50) COLLATE Latin1_General_CI_AS NULL
);

CREATE TABLE table_interch_quantity (
	spir_project_id int NULL,
	final_material_code varchar(40) COLLATE Latin1_General_CI_AS NULL,
	spir_maintainance_code_value varchar(1) COLLATE Latin1_General_CI_AS NULL,
	[position] int NULL,
	interch_qty_one_machine int NULL,
	interch_qty_all_machines int NULL,
	inspire_interch_quantity_id int DEFAULT NEXT VALUE FOR interch_quantity_id_seq NOT NULL,
	selected_activity_id int NULL,
	CONSTRAINT table_interch_quantity_pk PRIMARY KEY (inspire_interch_quantity_id)
);

CREATE TABLE table_activity_to_maintainance (
	spir_maintainance_code varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	selected_activity_id int NOT NULL,
	spir_project_id int NOT NULL,
	spir_maintainance_code_value varchar(1) COLLATE Latin1_General_CI_AS NULL,
	created_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	creation_date smalldatetime NULL,
	updated_by varchar(20) COLLATE Latin1_General_CI_AS NULL,
	update_date smalldatetime NULL,
	original_maintenance_code varchar(50) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT spir_activity_to_maintainance_pk PRIMARY KEY (spir_maintainance_code,selected_activity_id,spir_project_id),
	CONSTRAINT table_activity_to_maintainance_fk FOREIGN KEY (spir_project_id,selected_activity_id) REFERENCES table_activities(spir_project_id,selected_activity_id),
	CONSTRAINT table_activity_to_maintainance_fk_1 FOREIGN KEY (spir_project_id) REFERENCES table_project(spir_project_id)
);

CREATE TABLE table_interch_items (
	spir_project_id int NOT NULL,
	group_id int NOT NULL,
	section_number varchar(30) COLLATE Latin1_General_CI_AS NOT NULL,
	material_code_path varchar(4000) COLLATE Latin1_General_CI_AS NOT NULL,
	assembly_drawing varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	balloon_number varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	tot_qty_one_machine int NOT NULL,
	id varchar(4000) COLLATE Latin1_General_CI_AS NOT NULL,
	interch_order int NULL,
	interch_tot_qty_one_machine int NULL,
	interch_tot_qty_all_machines int NULL,
	interch_part_pos_no varchar(200) COLLATE Latin1_General_CI_AS NULL,
	english_material_code_desc varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	material_code varchar(40) COLLATE Latin1_General_CI_AS NOT NULL,
	serialnumbers varchar(4000) COLLATE Latin1_General_CI_AS NULL,
	remarks varchar(2) COLLATE Latin1_General_CI_AS NULL,
	[position] int NULL,
	maintenance_code varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	CONSTRAINT table_interch_items_PK PRIMARY KEY (id)
);